config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :posts

  resources :categories

  resources :users

	 match 'changeActiveUsers/:userid'  => 'users#changeActive'
	 match 'login_as/:userid'  => 'users#loginAs'
	 match 'change_password/:id'  => 'users#chPw'
	 match 'upload_category_image/:category_id'  => 'categories#upload_image'
	 match 'delete_category_image/:category_id'  => 'categories#delete_image'
	 match 'list_by_category/:category_id'  => 'posts#listByCategory'
	 match 'new_by_category/:category_id'  => 'posts#newPost'

   root :to => 'posts#index'

   match ':controller(/:action(/:id))(.:format)'

	 match 'login'  => 'users#login', :as => :login
	 match 'logout'  => 'users#logout', :as => :logout
	 match 'register'  => 'users#new', :as => :register
	 match 'lost_password'  => 'users#get_lost_password', :as => :lost_password

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :account_type, :email, :name, :password, :username


	validates_uniqueness_of :username
  validates_presence_of :username
  validates_presence_of :email
  validates_presence_of :name
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_format_of :username, :with => /\A([a-z0-9_]+)\Z/i


  ADMIN="Admin"
  BLOGGER ="Blogger"
  READER ="Reader"

  USER_TYPES = [ADMIN , BLOGGER, READER]

  attr_reader :password

  def password=(pw)
    salt = [Array.new(6){rand(256).chr}.join].pack("m").chomp
    self.password_salt, self.password_hash =
      salt, Digest::MD5.hexdigest(pw + salt)
  end

  def password_is?(pw)
    Digest::MD5.hexdigest(pw + password_salt) == password_hash
  end





end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_filter(:only => [:edit , :update , :show, :chPw, :chPwUpdate ] ) { |c| c.auth  [ {:types =>  [User::BLOGGER, User::READER] , :condition => lambda{|params,session| params[:id].to_i == session[:userid]} } , {:types => [User::ADMIN]} ]  }
 before_filter(:only => [:destroy, :changeActive , :index, :loginAs] ) { |c| c.auth  [ {:types =>  [User::ADMIN]  }]  }


  #captcha
  include SimpleCaptcha::ControllerHelpers


  def chPw
    @user = User.find(params[:id])
  end

  def chPwUpdate
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = 'Contraseña cambiada correctamente.'
      redirect_to(edit_user_path(@user)) 
    else
      render :action => "chPw" 
    end
  end

  # GET /users
  # GET /users.json
  def index
		@users = initialize_grid(User, {})

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end


	def login
		render
	end



  def verifyLogin
       @user = User.find_by_username_and_active(params[:login] ,  true)
      if @user and @user.password_is? params[:password]
        #TODO user should not be kept in the session because it can be modified (when user changes the profile session user should be loaded again)
         session[:userid] = @user.id
         flash[:notice] = 'login correct'
      else
         flash[:notice] = "Usuario, contraseña incorrectos o usuario no activo"
      end
       redirect_to :controller => 'posts' ,  :action => "index"

  end







	 def logout
    session.clear()
    redirect_to :controller => 'posts' ,  :action => "index"
  end


       def get_lost_password
                render
        end

        def lost_password
  				if simple_captcha_valid?
                username = params[:username]
                password  = [Array.new(8){rand(256).chr}.join].pack("m").chomp
                user = User.find_by_username_and_active(username, true)
                if user
                        user.password = password
                        if(user.save)
                                Notifier.lost_password(user.email,username, password).deliver
                                flash[:notice] =  'Contraseña enviada a la dirección de correo asociada'
                        else
                                flash[:notice] = 'No se ha podido generar una nueva contraseña'
                        end
                else
                        flash[:notice] = "User does not exist or is not active"
     										 render 'get_lost_password'
      									return
                end
  					else
               flash[:notice] = "Captcha not valid"
   						 render 'get_lost_password'
		    return
		  end
            redirect_to :controller=> "posts" , :action => 'index'
        end







	 def changeActive
    @user = User.find(params[:userid])

    @user.active = (! @user.active)
    if @user.save
			Notifier.user_change_active(@user.email, @user.username, @user.active).deliver
      flash[:notice] = 'Estado cambiado.'
     else
      ActiveRecord::Base.logger.warn   "errors saving user"
      @user.errors.each{|attr,msg|  ActiveRecord::Base.logger.warn   "#{attr} - #{msg}" }
      flash[:notice] = 'Estado no cambiado.'
    end
    redirect_to(users_url)
  end

  def loginAs
         session[:userid] = params[:userid]
         flash[:notice] = "login correct"
	       redirect_to :controller => 'posts' ,  :action => "index"

  end





  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

		if simple_captcha_valid?
			@user.active = false
      if @user.save
					Notifier.user_created(@user.username).deliver
					flash[:notice] = 'User was successfully created.'
         redirect_to :controller => "posts" ,:action => "index"
      else
        render :action => "new" 
      end
		else
				flash[:notice] = "Captcha not valid"
        render :action => "new" 
		end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_salt %><br />
    <%= f.text_field :password_salt %>
  </div>
  <div class="field">
    <%= f.label :password_hash %><br />
    <%= f.text_field :password_hash %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account_type %><br />
    <%= f.text_field :account_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/chPw.html.erb
<h1>Changing password for:</h1> <%= @user.username%>

<%=   form_for @user, { :action => "chPwUpdate" }   do |f| %>
  	  <% if @user.errors.any? %>
	    <div id="error_explanation">
		<h2><%= t :error_update, :count => @user.errors.count %></h2>	
	
	      <ul>
	      <% @user.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>



  <p>
   <%= t('password') %> : <br />
    <%= f.password_field :password %>
  </p>


  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/edit.html.erb
<h1>Changing profile</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br/>
To change password click <%= link_to "here" , :action => 'chPw' , :id => @user.id %>
<br/>
<%= link_to 'Show', @user %> 

app/views/users/get_lost_password.html.erb
<div class="title"><h3><%= t('generate_new_password') %> </h3></div>
<div class="fieldset-container">
<fieldset class="Label-Left">
<div class="fieldset-content">


<p> If the username exists and is active you will receive an email with the new password generated at the address registered with that user </p>


<br/>

<%= form_tag(:action => 'lost_password') do %>
<p>
 Username:
  <%= text_field_tag :username %>
</p>

	<%= show_simple_captcha %>

  <%= submit_tag 'New password request' %>
<% end %>
<hr></hr>
<p>
<%= link_to t('register'), register_path %>
</p>
<br />
<p>
<%= link_to t('login'), login_path %>
</p>
<br />
</div>
</fieldset>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<%= grid(@users, :show_filters => :always) do |user|

    user.column :name => t('type'), :attribute => 'account_type' , :custom_filter => User::USER_TYPES.map{|o| [t('userType' + o) , o ]} do |u|
            t('userType' + u.account_type)
    end

    user.column  :name => t('username') , :attribute => 'username' do |u|
      u.username
    end

    user.column  :name => t('name') , :attribute => 'name' do |u|
      u.name
    end
    user.column  :name => t('email') , :attribute => 'email' do |u|
      u.email
    end

    user.column  :name => t('active') , :attribute => 'active' do |u|
      u.active ? "Sí" : "No"
    end
    user.column  :name => t('creation_date') , :attribute => 'created_at' , :filter => false do |u|
      u.created_at.strftime("%d.%m.%Y")
    end

    user.column  :name => t('view')  do |u|
      link_to t(:view), u
    end

    user.column  :name => t('edit')  do |u|
       link_to t(:edit), edit_user_path(u)
    end

    user.column  :name => 'Change state'  do |u|
      link_to u.active? ? 'Inactivate' : 'Aactivate', :action=>'changeActive' , :userid => u.id
    end
    user.column  :name => t('login_as')  do |u|
      link_to 'Login as', :action=>'loginAs' , :userid => u.id
    end

    user.column :name => t('delete') do |u|
     link_to 'Destroy', u, :method => :delete, :confirm => 'Are you sure?' 
    end

end %>

app/views/users/login.html.erb
<h1>Login</h1>


<br/>
<%= form_tag(:action => 'verifyLogin') do %>


<p>
  Username
  <%= text_field_tag :login, params[:login] %>
</p>
<br/>
<p>
  Password
  <%= password_field_tag :password, params[:password] %>
</p>

  <%= submit_tag t("login") %>
<% end %>

<br><br>

</p>
<p>
<h2><%= link_to t('register') , register_path %></h2>
</p>
<p>
<%= link_to t('generate_new_password'), lost_password_path %>

app/views/users/new.html.erb
<h1>Register new user</h1>


<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<p>
When your registered user is activated by an administrator you will receive an email to the address indicated in this form.
</p>
 <div class="field">
    <%= f.label :account_type %> <br />
 <%= f.select  "account_type" ,      User::USER_TYPES.map{ |ut| [ t("userType" + ut.to_s), ut  ]   }   %>
 
  </div>

 <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
	 <%= show_simple_captcha %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>





<% end %>







<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<h1>User's profile</h1>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>


<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Account type:</b>
  <%= @user.account_type %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> 