config/routes.rb
Blog::Application.routes.draw do
  resources :comments

  resources :posts

  resources :categories

  resources :users

	 match 'changeActiveUsers/:userid'  => 'users#changeActive'
	 match 'login_as/:userid'  => 'users#loginAs'
	 match 'change_password/:id'  => 'users#chPw'
	 match 'upload_category_image/:category_id'  => 'categories#upload_image'
	 match 'delete_category_image/:category_id'  => 'categories#delete_image'
	 match 'list_by_category/:category_id'  => 'posts#listByCategory'
	 match 'new_by_category/:category_id'  => 'posts#newPost'

   root :to => 'posts#index'

   match ':controller(/:action(/:id))(.:format)'

	 match 'login'  => 'users#login', :as => :login
	 match 'logout'  => 'users#logout', :as => :logout
	 match 'register'  => 'users#new', :as => :register
	 match 'lost_password'  => 'users#get_lost_password', :as => :lost_password

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Bogdana's blog</title>
<link href="/css/styles.css" rel="stylesheet" type="text/css">
</head>
<body>

<div class="wrapper">
	<header>
    	<div class="logo"></div>
        <nav>
            <ul id="navlist">
						<li><%= link_to "Blog", posts_path  %></li>
						<% if session[:userid]  %>
						<% type = User.find(session[:userid]).account_type%>	
						<% if type == User::BLOGGER || type == User::ADMIN  %>
							<li><%= link_to "Categories", categories_path  %></li>
						<% if type == User::ADMIN  %>
								 <li><%= link_to "Users", users_path  %></li>
						<% end %>	
						<% end %>	
						<li><%= link_to "Profile", User.find(session[:userid])  %></li>
						<li><%= link_to "Logout", logout_path  %></li>
						<% else %>	
						<li><%= link_to "Login", login_path %></li>
						<% end %>	



            </ul>
        </nav>
        <div class="clearfloat"></div>
    </header>
    <div class="bodyContainer">
				<section>
						<% if session[:userid]  %>
							<b>Logged as:</b> <%= User.find(session[:userid]).username %>  
							<b>Account type:</b> <%= t('userType' + User.find(session[:userid]).account_type) %> 
						<% else %>
								Not logged
						<% end %>
					<hr/>	
				</section>
        <section>
            <p style="color: red">
							<%= flash[:notice] %>
            </p>
        </section>
        <section>
            <p>
							<%= yield %>
            </p>
        </section>
    </div>
    <div class="clearfloat"></div>
    <footer>
        <p>
            Copyright &copy; Your Company Name. All rights reserved. Designed by <a href="http://www.free-responsive-templates.com" title="free responsive templates">Free Responsive Templates</a>, Validation 
            <a class="footerLink" href="http://validator.w3.org/check/referer" title="This page validates as HTML5"><abbr title="HyperText Markup Language">HTML5</abbr></a> | 
            <a class="footerLink" href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS3</abbr></a>
        </p>
    </footer>
</div>

</body>
</html>